[tool.black]
line-length = 120

[tool.poetry]
name = "compilesketches"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "3.11.2"
GitPython = "3.1.31"
PyGithub = "1.58.1"
PyYAML = "6.0"
semver = "2.13.0"

[tool.poetry.group.dev.dependencies]
black = "23.3.0"
codespell = "2.2.4"
coverage = "7.2.2"
pytest = "7.3.2"
pytest-mock = "3.10.0"
flake8 = "6.0.0"
pep8-naming = "0.13.3"
yamllint = "1.30.0"

[tool.poetry.group.external]
# Provided only for use by boards platforms
# NOTE: This group is a temporary workaround that will be removed at the 2.0.0 release of the action.
optional = true

[tool.poetry.group.external.dependencies]
pyserial = "3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
